In [30]:
import pandas as pd
import numpy as np
import plotly.express as px

In [31]:
df=pd.read_csv("kenya food data.csv")

In [32]:
df

,date,admin1,admin2,market,latitude,longitude,category,commodity,unit,priceflag,pricetype,currency,price,usdprice
0,#date,#adm1+name,#adm2+name,#loc+market+name,#geo+lat,#geo+lon,#item+type,#item+name,#item+unit,#item+price+flag,#item+price+type,#currency,#value,#value+usd
1,15/01/2006,Coast,Mombasa,Mombasa,-4.05,39.666667,cereals and tubers,Maize,1 KG,actual,Wholesale,KES,16.13,0.2235
2,15/01/2006,Coast,Mombasa,Mombasa,-4.05,39.666667,cereals and tubers,Maize,90 KG,actual,Wholesale,KES,1480,20.5041
3,15/01/2006,Coast,Mombasa,Mombasa,-4.05,39.666667,pulses and nuts,Beans,1 KG,actual,Wholesale,KES,33.63,0.4659
4,15/01/2006,Coast,Mombasa,Mombasa,-4.05,39.666667,pulses and nuts,Beans,90 KG,actual,Wholesale,KES,3246,44.9705
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18316,15/02/2024,North Eastern,Garissa,Dagahaley (Daadab),0.185656,40.291621,miscellaneous food,NaN,200 G,forecast,Retail,KES,0,0
18317,15/02/2024,North Eastern,Garissa,Dagahaley (Daadab),0.185656,40.291621,miscellaneous food,Sugar,1 KG,forecast,Retail,KES,0,0
18318,15/02/2024,North Eastern,Garissa,Dagahaley (Daadab),0.185656,40.291621,oil and fats,Oil (vegetable),L,forecast,Retail,KES,0,0
18319,15/02/2024,North Eastern,Garissa,Dagahaley (Daadab),0.185656,40.291621,pulses and nuts,Beans,1 KG,forecast,Retail,KES,0,0
18320,15/02/2024,North Eastern,Garissa,Dagahaley (Daadab),0.185656,40.291621,vegetables and fruits,NaN,Unit,forecast,Retail,KES,0,0

In [33]:
df.isnull().sum()

date            0
admin1          0
admin2          0
market          0
latitude        0
longitude       0
category      570
commodity    6984
unit            0
priceflag       0
pricetype       0
currency        0
price           0
usdprice        0
dtype: int64

In [34]:
df.dropna(inplace=True)

In [35]:
df["commodity"].value_counts()

Beans              3727
Maize              3161
Potatoes           1629
Rice                829
Oil (vegetable)     655
Sugar               473
Bread               184
Milk                184
                     83
#item+name            1
Name: commodity, dtype: int64

In [36]:
df

,date,admin1,admin2,market,latitude,longitude,category,commodity,unit,priceflag,pricetype,currency,price,usdprice
0,#date,#adm1+name,#adm2+name,#loc+market+name,#geo+lat,#geo+lon,#item+type,#item+name,#item+unit,#item+price+flag,#item+price+type,#currency,#value,#value+usd
1,15/01/2006,Coast,Mombasa,Mombasa,-4.05,39.666667,cereals and tubers,Maize,1 KG,actual,Wholesale,KES,16.13,0.2235
2,15/01/2006,Coast,Mombasa,Mombasa,-4.05,39.666667,cereals and tubers,Maize,90 KG,actual,Wholesale,KES,1480,20.5041
3,15/01/2006,Coast,Mombasa,Mombasa,-4.05,39.666667,pulses and nuts,Beans,1 KG,actual,Wholesale,KES,33.63,0.4659
4,15/01/2006,Coast,Mombasa,Mombasa,-4.05,39.666667,pulses and nuts,Beans,90 KG,actual,Wholesale,KES,3246,44.9705
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18313,15/02/2024,North Eastern,Garissa,Dagahaley (Daadab),0.185656,40.291621,cereals and tubers,Potatoes,1 KG,forecast,Retail,KES,0,0
18314,15/02/2024,North Eastern,Garissa,Dagahaley (Daadab),0.185656,40.291621,cereals and tubers,Rice,1 KG,forecast,Retail,KES,0,0
18317,15/02/2024,North Eastern,Garissa,Dagahaley (Daadab),0.185656,40.291621,miscellaneous food,Sugar,1 KG,forecast,Retail,KES,0,0
18318,15/02/2024,North Eastern,Garissa,Dagahaley (Daadab),0.185656,40.291621,oil and fats,Oil (vegetable),L,forecast,Retail,KES,0,0
18319,15/02/2024,North Eastern,Garissa,Dagahaley (Daadab),0.185656,40.291621,pulses and nuts,Beans,1 KG,forecast,Retail,KES,0,0

In [37]:
df.drop("category",axis=1,inplace=True)

In [38]:
df.to_csv("cleaned data.csv")